-- 1. What are the names of all the countries in the country table?

SELECT country_name
FROM country;

--  2. What is the total number of customers in the customers table?

SELECT COUNT( DISTINCT customer_id) AS Number_of_Customers
FROM customers;

--  3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?

SELECT 

ROUND(AVG(age))AS Average_Age_Client
FROM customers
WHERE can_email = 'yes' ;


--  4. How many orders were made by customers aged 30 or older?

SELECT COUNT(o.order_id) AS Orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE c.age > 29;

--  5. What is the total revenue generated by each product category?

SELECT 
DISTINCT p.category,
b.product_id,
p.price AS price_of_product,
COUNT(b.order_id) as orders,
SUM(COUNT(b.order_id) * p.price) OVER(PARTITION BY  p.category) AS Revenue_of_category

FROM products p
LEFT JOIN baskets b
ON p.product_id = b.product_id
GROUP BY 1,2,3;


SELECT

category,
rev
FROM (SELECT 
DISTINCT p.category,
b.product_id,
 p.price,
COUNT(b.order_id) as orders,
SUM(COUNT(b.order_id) * p.price) OVER(PARTITION BY p.category) AS rev

FROM products p
LEFT JOIN baskets b
ON p.product_id = b.product_id
GROUP BY 1,2,3
) as f

;

SELECT SUM(subt) AS ter
FROM (
    SELECT b.order_id, COUNT(b.order_id) * p.price AS subt
    FROM baskets b
    JOIN products p ON b.product_id = p.product_id
    GROUP BY b.order_id
) AS subquery
;

-- 6. What is the average price of products in the 'food' category?
SELECT

category,
rev
FROM (SELECT 
DISTINCT p.category,
b.product_id,
 p.price,
COUNT(b.order_id) as orders,
SUM(COUNT(b.order_id) * p.price) OVER(PARTITION BY p.category) AS rev

FROM products p
LEFT JOIN baskets b
ON p.product_id = b.product_id
WHERE p.category = 'food'
GROUP BY 1,2,3
) as f

;

--  7. How many orders were made in each sales channel (sales_channel column) in the orders table?

SELECT
sales_channel, 
COUNT(order_id) AS Order_by_channel
FROM orders
GROUP BY 1; 

SELECT * FROM orders;

--  8. What is the date of the latest order made by a customer who can receive marketing emails?


SELECT 
	MAX(o.date_shop),
	c.can_email

FROM orders o 
JOIN customers c
ON o.customer_id = c.customer_id
WHERE c.can_email = 'yes'
ORDER BY o.date_shop DESC;


--  9. What is the name of the country with the highest number of orders?

SELECT c.country_name,
COUNT(o.order_id)
FROM country c
JOIN orders o
ON c.country_id = o.country_id
GROUP BY 1
ORDER BY 2 DESC ; 

--  10. What is the average age of customers who made orders in the 'vitamins' product category? 

SELECT 
AVG(c.age) AS average_age_customer,
p.category
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN baskets b 
ON o.order_id = b.order_id
JOIN products p 
ON b.product_id = p.product_id
WHERE p.category = 'vitamins';